server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kamba_adima_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true